### ISSUE TITLE
Multi Location issue

### ISSUE THREAD

**Issue by ipaquetteMuniles** [csm10495/pyhtcc#17]
When I have one building or location in the mytotalconnectcomfort, there is no problem. Otherwise, when I add up a second location, it fells ? Can we have a multi locations system ? Here are the errors that pop up : 

Traceback (most recent call last):
  File "C:\Users\ipaquette\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyhtcc\pyhtcc.py", line 598, in _set_location_id_from_result
    self._locationId = int(result.url.split("portal/")[1].split("/")[0])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Locations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ipaquette\Documents\app\serveur_python\ResideoServer.py", line 282, in <module>
    user = PyHTCC(email, mdp)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ipaquette\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyhtcc\pyhtcc.py", line 478, in __init__
    self.authenticate()
  File "C:\Users\ipaquette\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyhtcc\pyhtcc.py", line 
491, in authenticate
    return self._do_authenticate()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ipaquette\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyhtcc\pyhtcc.py", line 
572, in _do_authenticate
    self._set_location_id_from_result(result)
  File "C:\Users\ipaquette\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyhtcc\pyhtcc.py", line 
601, in _set_location_id_from_result
    self._locationId = int(re.findall(r"locationId=(\d+)", result.text)[0])
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by csm10495** [comment]
Yeah this is a known issue: it doesn't work with multiple locations on the same account right now.

I'm pretty busy lately unfortunately so may not be able to get to this for a while. 

If someone has a PR, I'd be happy to review.

**Comment by ipaquetteMuniles** [comment]
Hi, thanks for your quick response !

I trick the web platform by adding thermostasts from differents location, but build in the same location section, not physically.

That should do it ! Kind regards

Iohann

________________________________
De : Charles Machalow ***@***.***>
Envoyé : lundi 5 août 2024 12:14
À : csm10495/pyhtcc ***@***.***>
Cc : Iohann Paquette ***@***.***>; Author ***@***.***>
Objet : Re: [csm10495/pyhtcc] Multi Location issue (Issue #17)


Yeah this is a known issue: it doesn't work with multiple locations on the same account right now.

I'm pretty busy lately unfortunately so may not be able to get to this for a while.

If someone has a PR, I'd be happy to review.
