### ISSUE TITLE
Install fails with missing dependency (gspread)

### ISSUE THREAD

**Issue by rayneram** [csm10495/pyhtcc#3]
Clean install on Windows 10:

```
C:\>pip install pyhtcc
Collecting pyhtcc
  Downloading pyhtcc-0.1.3.tar.gz (7.3 kB)
Collecting csmlog
  Downloading csmlog-0.22.0.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-f0b1g9g3\csmlog\setup.py", line 6, in <module>
        from csmlog import __version__
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-f0b1g9g3\csmlog\csmlog\__init__.py", line 14, in <module>
        from csmlog.google_sheets_handler import GSheetsHandler
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-f0b1g9g3\csmlog\csmlog\google_sheets_handler.py", 
        line 20, in <module>
        import gspread
    ModuleNotFoundError: No module named 'gspread'
```

Running `pip install gspread` and then `pip install pyhtcc` works fine.

**Comment by csm10495** [comment]
Thanks for reporting this. It's actually an issue with my csmlog module. Will try to fix.

I had hit this before and couldn't figure it out but it just hit me that setup.py is importing things that it won't have till after install. That's the issue.

**Comment by csm10495** [comment]
Fixed with https://github.com/csm10495/csmlog/commit/060d086f34afe5863112466c2395279376503f6a Closing out. Thanks for reporting.
